### ISSUE TITLE
File name is being set to _id

### ISSUE THREAD

**Issue by hluz** [jalik/jalik-ufs-gridfs#2]
When uploading a file, the file name in the mongodb collection.files is being set to _id instead of the file name uploaded. This causes the url to be based on _id.extension instead of filename. for images to be displayed in the app, not a big deal, but when downloading the file, it does matter.

**Comment by rodrigok** [comment]
@hluz the url is _id.extension not because we save the _id in file name since this is mounted based in the file collection and not based in GridFS collections, you can look at your file collection, the name will be their.

This issue is related with https://github.com/jalik/jalik-ufs/ and not the stores, maybe we can allow users to pass a custom fileId when upload starts https://github.com/jalik/jalik-ufs/blob/master/ufs-uploader.js#L56.

@jalik what do you think?

**Comment by jalik** [comment]
I actually chose to use this ID in the url to avoid any future break in case of file renaming, all old links will still be valid if the file name changes.

Solution 1 : send a HTTP header which forces to download the file with the real file name
Solution 2 : change the file URL using a pattern like `http://domain.com/{store}/{fileId}/{filename}.{ext}`, but that would break links used by existing apps and it needs more work to make a patch that would update existing records in the file collection to use this new URL pattern..

What do you think ? any other proposition ?

**Comment by jalik** [comment]
I close this issue since it was fixed in the main package `jalik:ufs`.
